layout_spectrum: 0.2744681
color:
  saturation: 0.8654243
  brandStrength: 0.281326
  lightness: 0.2737505
  brandColors:
    - '#010E4B'
    - '#D9DEFC'
    - '#0165B5'
    - '#4B395C'
    - '#A36F90'
  rhythmicContrast: 0.1405475
typography_spectrum: 0.6851064
name: Simmons Tobias
