collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.6851064
color:
  saturation: 0.8654243
  brandStrength: 0.2319149
  lightness: 0.2737505
  brandColors:
    - '#010E4B'
    - '#D9DEFC'
    - '#0165B5'
    - '#4B395C'
    - '#A36F90'
  rhythmicContrast: 0.1405475
layout_spectrum: 0.2744681
name: Simmons Tobias
